/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar explicitly excludes 'api' directory which has its own sidebar
  tutorialSidebar: [
    'intro',
    'getting_started',
    {
      type: 'category',
      label: 'Features',
      items: [
        {
          type: 'autogenerated',
          dirName: 'features',
        },
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      items: [
        {
          type: 'autogenerated',
          dirName: 'deployment',
        },
      ],
    },
    {
      type: 'category',
      label: 'ServerlessLLM Store',
      items: [
        {
          type: 'autogenerated',
          dirName: 'store',
        },
      ],
    },
    {
      type: 'category',
      label: 'Developer Guide',
      items: [
        {
          type: 'autogenerated',
          dirName: 'developer',
        },
      ],
    },
    {
      type: 'category',
      label: 'Models',
      items: [
        {
          type: 'autogenerated',
          dirName: 'models',
        },
      ],
    },
    {
      type: 'category',
      label: 'Community',
      items: [
        {
          type: 'autogenerated',
          dirName: 'community',
        },
      ],
    },
  ],
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
